config/routes.rb
Rails.application.routes.draw do

  mount SimpleDiscussion::Engine => "/forum"
  resources :taichi_files
  get 'users_dashboard/videos'
  get 'users_dashboard/files'
  get 'users_dashboard/gallery'
  get 'users_dashboard/settings'
  resources :clubs
  resources :videos
  get 'dashboard/overview', as: :dashboard
  get 'dashboard/settings', as: :settings
  get 'dashboard/members', as: :members
  get 'dashboard/blog', as: :blog
  get 'dashboard/calendar', as: :calendar
  get 'dashboard/resources', to: "dashboard#videos", as: :club_videos

  resources :contents
  resources :posts
  devise_for :users
  resources :events
  get 'site/index'
  get '/about', to: "site#about", as: "/about"
  get '/gallery', to: "site#gallery", as: "/gallery"
  get '/forms', to: "site#forms", as: "/forms"

  unauthenticated :users do
    root to: "site#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action do |controller|
    unless controller.send(:is_admin?)
      flash[:info] = "you are admin"
      redirect_to root_url
    end
    @admin = current_user
  end

  def videos
    @videos = Video.all
  end

  def overview
    @videos = Video.all
    @users = User.all
    @posts = Post.all
  end

  def settings
  end

  def members
    @users = User.all
  end

  def blog
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  def calendar
  end

  private

    def is_admin?
      current_user.admin?
    end

    def set_club
      @club = Club.first
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav ml-auto" role="navigation">
            <li class="nav-item">
              <%= link_to "Forum", simple_discussion_path, class: "nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to "Overview", dashboard_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path,method: :delete, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/dashboard/_sidebar.html.erb
  <nav class="card">
    <div class="media pt-3">
      <p class="mr-3">
      </p>
      <div class="media-body">
        <h4><%= current_user.name %></h4>
        <% if current_user.admin? %>
          <span class="badge badge-light px-3 py-2">
            admin
          </span>
        <% end %>
      </div>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="pt-1">
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to "Overview", dashboard_path, class: "nav-link #{'active' if current_page?(dashboard_path)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to "Blog", blog_path, class: "nav-link #{'active' if current_page?(blog_path)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to "Members", members_path, class: "nav-link #{ 'active' if current_page?(members_path)}"%>
        </li>
        <li class="list-group-item">
          <%= link_to "Files", taichi_files_path, class: "nav-link #{ 'active' if current_page?(taichi_files_path)}"%>
        </li>
        <li class="list-group-item">
          <%= link_to "Videos", club_videos_path, class: "nav-link #{ 'active' if current_page?(club_videos_path)}"%>
        </li>
        <li class="list-group-item">
          <%= link_to "Settings", settings_path, class: "nav-link #{ 'active' if current_page?(settings_path)}"%>
        </li>
      </ul>
    </div>
  </nav>

app/views/dashboard/blog.html.erb
<% title "Our Blog | Tai Chi" %>
<div class="container">
  <div class="py-2">
    <h4 class="text-muted">
      Club Blog
    </h4>
    <hr/>
    <%= link_to 'Create new post', "#post-modal", class: "btn btn-primary", data: { target: "#post-modal", toggle: "modal"} %>
  </div>
  <div class="py-4">
    <% @posts.each do |post| %>
      <div class="article-card">
        <div class="py-4">
          <h4 class="font-weight-bold"><%= link_to post.title, post %></h4>
          <p class="py-2 text-muted">
          <%= pluralize(post.impressionist_count, 'view') %>
          - posted <%= time_ago_in_words(post.created_at) %>  ago
          - by: <%= post.user.full_name %>
          </p>
          <% if !@admin.nil? %>
            <%= link_to 'Edit', edit_post_path(post) %> | 
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
          <hr/>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- SignUp Modal -->
<div class="modal fade" id="post-modal" tabindex="-1" role="dialog" aria-labelledby="post-modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header p-3">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add new post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "posts/form", post: @post%>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/calendar.html.erb
<h1>Dashboard#calendar</h1>
<p>Find me in app/views/dashboard/calendar.html.erb</p>

app/views/dashboard/members.html.erb
<div class="container">
  <div class="py-2">
    <h4 class="text-muted">
      Club Members
    </h4>
    <hr/>
    <%= link_to "Invite a member", new_user_invitation_path, class: "btn btn-outline-primary"%>
  </div>
  <div class="card py-4 mx-2">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table mt-2">
          <thead>
            <tr>
              <th>Name</th>
              <th>Surname</th>
              <th>email</th>
              <th>admin</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user|%>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.admin %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
</div>

app/views/dashboard/overview.html.erb
<div class="container">
  <div class="py-2">
    <h4 class="text-muted">
      Hello, <%= @admin.first_name %>
    </h4>
    <hr/>
  </div>
  <div class="row">
    <div class="data-show">
      <h4>Posts</h4>
      <h1>
        <%= @posts.count %>
      </h1>
    </div>
    <div class="data-show">
      <h4>Members</h4>
      <h1>
        <%= @users.count %>
      </h1>
    </div>
    <div class="data-show">
      <h4>Videos</h4>
      <h1>
        <%= @videos.count %>
      </h1>
    </div>
    <div class="data-show">
    </div>
    <div class="data-show">
    </div>
  </div>
</div>

app/views/dashboard/resources.html.erb
<% title "Resources | Tai Chi" %>
<div class="container">
  <div class="py-2">
    <h4 class="text-muted">
      Club Blog
    </h4>
    <hr/>
  </div>
</div>

app/views/dashboard/settings.html.erb
<div class="container">
  <div class="py-2">
    <h3 class="text-muted">
      Club Settings
    </h3>
    <hr/>
  </div>
  <div class="py-2">
    <div class="display-sec">
      <div class="d-flex flex-md-row flex-column bd-highlight">
        <div class="bd-highlight w-100">
          <div class="card p-4 m-1">
            <h6>Membership &nbsp; <a href="#member-modal" data-toggle="modal" data-target="#member-modal">update</a></h6>
            <p class="py-2">
              <em>Students</em>
              <%= @club.membership_students %>
              <br/>
              <em>External members</em>
              <%= @club.membership_external %>
            </p>
            <div class="modal fade" id="member-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update your hourly rate</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @club, local: true) do |form| %>
                      <div class="py-4 mx-2">
                        <%= form.text_field :membership_students, class: "form-control form-control-lg", placeholder: "Membership for students"%>
                      </div>
                      <div class="py-4 mx-2">
                        <%= form.text_field :membership_external, class: "form-control form-control-lg", placeholder: "Membership for External members"%>
                      </div>
                      <div class="py-4 mx-2">
                        <%= form.submit "Update", class: "btn btn-success btn-lg"%>
                      </div>
                    <% end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bd-highlight w-100">
          <div class="card p-4 m-1">
            <h6>Class Times &nbsp; <a href="#times-modal" data-toggle="modal" data-target="#times-modal">update</a></h6>
            <p class="py-2">
              <%= @club.class_times%>
            </p>
            <div class="modal fade" id="times-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content mx-2">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update Class Times</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @club, local: true) do |form| %>
                      <div class="py-4 mx-2">
                        <%= form.label :class_times %>
                        <%= form.text_area :class_times, class: "form-control form-control-lg", placeholder: "add for both beginners & seniors", rows: 10%>
                      </div>
                      <div class="py-4 mx-2">
                        <%= form.submit "Update class times", class: "btn btn-success btn-lg"%>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bd-highlight w-100">
          <div class="card p-4 m-1">
            <h6>Dress Code &nbsp; <a href="#dress-modal" data-toggle="modal" data-target="#dress-modal">update</a></h6>
            <p class="py-2">
              <%= @club.dress_code%>
            </p>
          </div>
          <div class="modal fade" id="dress-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content mx-2">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Update Dress Code</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= form_with(model: @club, local: true) do |form| %>
                    <div class="py-4 mx-2">
                      <%= form.label :dress_code %>
                      <%= form.text_area :dress_code, class: "form-control form-control-lg", placeholder: "What can members wear?", rows: 10%>
                    </div>
                    <div class="py-4 mx-2">
                      <%= form.submit "Update dress code", class: "btn btn-success btn-lg"%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="py-4 display-sec">
      <h6><%= link_to "update club bio", edit_club_path(@club)%></h6>
      <p>
        <%= @club.content %>
      </p>
    </div>
    <div class="py-2">
      <h4 class="text-muted">
        Club Coach &amp; Socials
      </h4>
      <hr>
    </div>
    <div class="py-2">
      <div class="row">
        <div class="col-xs-12 col-md-4 col-lg-4">
          <div class="py-2 display-sec">
            <h6>Coach name  &nbsp; <a href="#coach-modal" data-toggle="modal" data-target="#coach-modal">update</a></h6>
            <p class="lead py-4">
              <%= @club.coach_name %>
            </p>
            <div class="modal fade" id="coach-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update your bio</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @club, local: true) do |form| %>
                      <div class="py-4">
                        <%= form.text_field :coach_name, class: "form-control form-control-lg", placeholder: "Name of your coach", required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.text_area :coach_bio, 'data-provider': :summernote, class: "form-control form-control-lg", placeholder: "Talk about your coach", rows: 15, required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.submit "Update", class: "btn btn-success btn-lg"%>
                      </div>
                    <% end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="pb-2 display-sec">
            <h6> Bio </h6>
            <p class="lead py-2 pr-4">
              <%= @club.coach_bio %>
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-md-4 col-lg-4">
          <div class="py-2 display-sec">
            <h6>Club Social Media  &nbsp; <a href="#social-modal" data-toggle="modal" data-target="#social-modal">update</a></h6>
            <div class="modal fade" id="social-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update club's social media links</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @club, local: true) do |form| %>
                      <div class="py-4">
                        <%= form.text_field :facebook, class: "form-control form-control-lg", placeholder: "facebook link", required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.text_field :instagram, class: "form-control form-control-lg", placeholder: "instagram link", required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.text_field :youtube, class: "form-control form-control-lg", placeholder: "youtube channel", required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.submit "Update", class: "btn btn-success btn-lg"%>
                      </div>
                    <% end%>
                  </div>
                </div>
              </div>
            </div>
            <p class="lead py-4">
              <%= link_to "https://facebook.com/#{@club.facebook}" do %>
                <span class="mx-2 fa fa-facebook fa-2x">
                </span>
              <% end %>
              <%= link_to "https://instagram.com/#{@club.instagram}" do %>
                <span class="mx-2 fa fa-instagram fa-2x">
                </span>
              <% end %>
              <%= link_to "https://youtube.com/#{@club.youtube}" do %>
                <span class="mx-2 fa fa-youtube fa-2x">
                </span>
              <% end %>
            </p>
          </div>
          <div class="py-2 display-sec">
            <h6>Club Contacts  &nbsp; <a href="#contacts-modal" data-toggle="modal" data-target="#contacts-modal">update</a></h6>
            <div class="modal fade" id="contacts-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update club's contacts</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @club, local: true) do |form| %>
                      <div class="py-4">
                        <%= form.text_field :contacts, class: "form-control form-control-lg", placeholder: "clubs email address", required: true%>
                      </div>
                      <div class="py-4">
                        <%= form.submit "Update", class: "btn btn-success btn-lg"%>
                      </div>
                    <% end%>
                  </div>
                </div>
              </div>
            </div>
            <p class="lead py-4">
              <a href="<%= @club.contacts %>">
                <span class="mx-2 fa fa-envelope fa-1x">
                </span>
              </a>
              <%= @club.contacts %>
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-md-4 col-lg-4">
          <div class="py-2 display-sec">
            <h6> Events Calendar </h6>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4 display-sec">
      <div class="py-2">
        <h4 class="text-muted">
          Profile Settings
        </h4>
        <hr/>
      </div>
      <div class="py-4">
        <%= link_to "Edit Details",settings_path %>
      </div>
      <div class="py-2">
        <%= link_to "Cancel Account",root_path,class:"text-muted" %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/videos.html.erb
<% title "Resources | Tai Chi" %>
<div class="container">
  <div class="py-2">
    <h4 class="text-muted">
      Club Videos
    </h4>
    <hr/>
  </div>
</div>