config/routes.rb
Rails.application.routes.draw do

  mount SimpleDiscussion::Engine => "/forum"
  resources :taichi_files
  get 'users_dashboard/videos'
  get 'users_dashboard/files'
  get 'users_dashboard/gallery'
  get 'users_dashboard/settings'
  resources :clubs
  resources :videos
  get 'dashboard/overview', as: :dashboard
  get 'dashboard/settings', as: :settings
  get 'dashboard/members', as: :members
  get 'dashboard/blog', as: :blog
  get 'dashboard/calendar', as: :calendar
  get 'dashboard/resources', to: "dashboard#videos", as: :club_videos

  resources :contents
  resources :posts
  devise_for :users
  resources :events
  get 'site/index'
  get '/about', to: "site#about", as: "/about"
  get '/gallery', to: "site#gallery", as: "/gallery"
  get '/forms', to: "site#forms", as: "/forms"

  unauthenticated :users do
    root to: "site#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord

  has_rich_text :content

  has_many_attached :images
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  validates_presence_of :title
  validates_presence_of :from
  validates_presence_of :until

  # TODO: only admins can create events
  #before_save :verify_admin

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  extend FriendlyId
  friendly_id :title, use: :slugged

  is_impressionable
  has_rich_text :content



  def slug_options
    [
      [:title],
      [:title, :created_at]
    ]
  end
end

app/models/taichi_file.rb
class TaichiFile < ApplicationRecord
  belongs_to :user
  has_one_attached :docs

  validates_presence_of :title, :docs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include SimpleDiscussion::ForumUser
  # associations
  has_many :events
  has_many :contents
  has_many :posts

  def full_name
    self.first_name.concat(' ').concat(self.last_name)
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/video.rb
class Video < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_admin

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to settings_url, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    def set_admin
      @admin = current_user if current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:about, :history, :dress_code, :class_times, :contacts, :coach_name, :coach_bio, :facebook, :instagram, :youtube, :membership_students, :membership_external, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_admin, except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to blog_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def set_admin
      @admin = current_user if current_user.try(:admin?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :content)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def gallery
  end
  def index
    redirect_to simple_discussion_path if user_signed_in?
  end

  def about
    @about = Content.where('content_type like ? ', 'about').first
  end
end

app/controllers/users_dashboard_controller.rb
class UsersDashboardController < ApplicationController
  def videos
    @videos = Video.all
  end

  def files
    @files = TaichiFile.all
  end

  def gallery
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title text
    content_for(:title) { text }
  end

  def meta_tag tags, text
    content_for :"meta_#{tags}", text 
  end

  def yield_meta_tag tags, default_text='' 
    content_for?(:"meta_#{tags}") ? content_for(:"meta_#{tags}") : default_text
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/taichi_files_helper.rb
module TaichiFilesHelper
end

app/helpers/users_dashboard_helper.rb
module UsersDashboardHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/users_dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mx-auto" role="navigation">
            <li class="nav-item">
              <%= link_to "Forum", simple_discussion_path, class: "nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to "Dashboard", users_dashboard_files_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Files", users_dashboard_files_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Videos", users_dashboard_videos_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Gallery", users_dashboard_gallery_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Settings", users_dashboard_settings_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path,method: :delete, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users_dashboard/_sidebar.html.erb
<div class="py-5 mx-2">
  <h4 class="text-center">
    <!-- user names here -->
  </h4>
<ul class="nav flex-column">
  <div class="py-4 text-center">
  </div>
  <div style="padding: 0px 50px;">
    <li class="nav-item">
      <%= link_to "Files", users_dashboard_files_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Videos", users_dashboard_videos_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Gallery", users_dashboard_gallery_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Settings", users_dashboard_settings_path, class: "nav-link"%>
    </li>
  </div>
</ul>
</div>

app/views/users_dashboard/files.html.erb
<div class="py-2">
  <h1 class="font-weight-bold py-4">Files</h1>
  <p class="lead py-2">Read or download files</p>
  <div class="card-columns">
    <% @files.each do |file|%>
      <% if file.docs.attached? %>
        <div class="card mb-4">
          <div class="text-center">
            <%= image_tag file.docs.preview(resize: "200x200") %>
          </div>
          <div class="card-body">
            <h4 class="card-title">
              <%=  link_to file.title, url_for(file.docs) %>
              <br/>
              <span class="font-weight-light" style="font-size: 0.8em">
                <%= time_ago_in_words(file.created_at)%> ago
              </span>
            </h4>
            <span class="badge badge-primary font-weight-light" style="font-size: 0.8em">
              <%= file.category %>
            </span>
            <p class="card-text">
              <%=  file.desc %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users_dashboard/gallery.html.erb
<h1>Gallery</h1>

app/views/users_dashboard/settings.html.erb
<div>
  <h4>
    Welcome to your settings
  </h4>
  <p class="lead py-4">
    Update your details
  </p>
  <div class="py-5">
    <p>
      email: <%= current_user.email %>
    </p>
  </div>
</div>

app/views/users_dashboard/videos.html.erb
<div>
  <h1 class="font-weight-bold py-4">Videos</h1>
  <p class="lead py-2">watch our videos</p>
  <div class="card-columns">
    <% @videos.each do |video|%>
      <div class="card mb-4">
        <div class="embed-responsive embed-responsive-4by3">
          <iframe class="embed-responsive-item" width="1280" height="720" src="https://www.youtube.com/embed/<%= video.youtube_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="card-body">
          <h4 class="card-title">
            <%=  link_to video.title, video %>
            <br/>
            <span class="font-weight-light" style="font-size: 0.8em">
              <%= time_ago_in_words(video.created_at)%> ago
            </span>
          </h4>
          <span class="badge badge-primary font-weight-light" style="font-size: 0.8em">
            <%= video.category %>
          </span>
          <p class="card-text">
            <%=  video.desc %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>