config/routes.rb
Rails.application.routes.draw do

  mount SimpleDiscussion::Engine => "/forum"
  resources :taichi_files
  get 'users_dashboard/videos'
  get 'users_dashboard/files'
  get 'users_dashboard/gallery'
  get 'users_dashboard/settings'
  resources :clubs
  resources :videos
  get 'dashboard/overview', as: :dashboard
  get 'dashboard/settings', as: :settings
  get 'dashboard/members', as: :members
  get 'dashboard/blog', as: :blog
  get 'dashboard/calendar', as: :calendar
  get 'dashboard/resources', to: "dashboard#videos", as: :club_videos

  resources :contents
  resources :posts
  devise_for :users
  resources :events
  get 'site/index'
  get '/about', to: "site#about", as: "/about"
  get '/gallery', to: "site#gallery", as: "/gallery"
  get '/forms', to: "site#forms", as: "/forms"

  unauthenticated :users do
    root to: "site#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/taichi_file.rb
class TaichiFile < ApplicationRecord
  belongs_to :user
  has_one_attached :docs

  validates_presence_of :title, :docs
end

app/controllers/taichi_files_controller.rb
class TaichiFilesController < ApplicationController
  before_action :set_taichi_file, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /taichi_files
  # GET /taichi_files.json
  def index
    @taichi_files = TaichiFile.all
    @taichi_file = TaichiFile.new
  end

  # GET /taichi_files/1
  # GET /taichi_files/1.json
  def show
  end

  # GET /taichi_files/new
  def new
    @taichi_file = TaichiFile.new
  end

  # GET /taichi_files/1/edit
  def edit
  end

  # POST /taichi_files
  # POST /taichi_files.json
  def create
    @taichi_file = TaichiFile.new(taichi_file_params)
    @taichi_file.user_id = current_user.id
    @taichi_file.docs.attach(params[:taichi_file][:docs])

    respond_to do |format|
      if @taichi_file.save
        format.html { redirect_to taichi_files_url, notice: 'Taichi file was successfully created.' }
        format.json { render :show, status: :created, location: @taichi_file }
      else
        format.html { render :new }
        format.json { render json: @taichi_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taichi_files/1
  # PATCH/PUT /taichi_files/1.json
  def update
    respond_to do |format|
      if @taichi_file.update(taichi_file_params)
        format.html { redirect_to taichi_files_url, notice: 'Taichi file was successfully updated.' }
        format.json { render :show, status: :ok, location: @taichi_file }
      else
        format.html { render :edit }
        format.json { render json: @taichi_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taichi_files/1
  # DELETE /taichi_files/1.json
  def destroy
    @taichi_file.destroy
    respond_to do |format|
      format.html { redirect_to taichi_files_url, notice: 'Taichi file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taichi_file
      @taichi_file = TaichiFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def taichi_file_params
      params.require(:taichi_file).permit(:title, :desc, :category, :user_id)
    end
end

app/helpers/taichi_files_helper.rb
module TaichiFilesHelper
end

app/views/taichi_files/_form.html.erb
<%= form_with(model: @taichi_file, local: true) do |form| %>
  <% if @taichi_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taichi_file.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @taichi_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mx-5">
    <div class="py-4 mx-2">
      <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "title", required: true%>
    </div>
    <div class="py-4 mx-2">
      <%= form.label :category%>
      <%= form.select :category, options_for_select(["General","Qigong", "Form"]), {}, class: "custom-select custom-select-lg"%>
    </div>
    <div class="py-4 mx-2">
      <%= form.text_area :desc, class: "form-control form-control-lg", placeholder: "File description"%>
    </div>
    <div class="py-4 mx-2">
      <%= form.label :file_to_uploaded%>
      <br/>
      <% if @taichi_file.docs.attached?%>
        <span class="font-italic">
          pdfs attached 
        </span>
        <p>
          <%= @taichi_file.docs.filename %>
        </p>
      <% end%>
      <span class="font-italic">
        pdfs are preferred
      </span>
      <%= form.file_field :docs, class: "form-control-file form-control-file-lg", required: true%>
    </div>
    <div class="py-4 mx-2">
      <%= form.submit "Add File", class: "btn btn-success btn-lg"%>
      <%= link_to 'Back', taichi_files_path, class: "mx-4 btn btn-danger btn-lg" %>
    </div>
  </div>
<% end%>

app/views/taichi_files/edit.html.erb
<h1>Editing Taichi File</h1>

<%= render 'form', taichi_file: @taichi_file %>

<%= link_to 'Show', @taichi_file %> |
<%= link_to 'Back', taichi_files_path %>

app/views/taichi_files/index.html.erb
<div class="container">
  <h1 class="font-weight-bold py-4">Files
    <button class="d-none d-lg-block btn btn-lg btn-primary" href="#taichi_files-modal" data-toggle="modal" data-target="#taichi_files-modal">
      add new file
    </button>
    <%= link_to "add new file", new_taichi_file_path, class: 'btn btn-lg btn-primary d-lg-none d-block'%>
  </h1>
  <div class="card-columns">
    <% @taichi_files.each do |t_files|%>
      <% if t_files.docs.attached? %>
        <div class="card mb-4">
          <div class="text-center">
          </div>
          <div class="card-body">
            <h4 class="card-title">
              <%=  link_to t_files.title, url_for(t_files.docs) %>
              <br/>
              <span class="font-weight-light" style="font-size: 0.8em">
                <%= time_ago_in_words(t_files.created_at)%> ago
              </span>
            </h4>
            <span class="badge badge-primary font-weight-light" style="font-size: 0.8em">
              <%= t_files.category %>
            </span>
            <p class="card-text">
              <%=  t_files.desc %>
            </p>
          </div>
          <div class="card-footer">
            <%= link_to "Edit", edit_taichi_file_path(t_files), class: "btn btn-light" %>
            <%= link_to "Delete", taichi_file_path(t_files), method: :delete, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="modal fade" id="taichi_files-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create new video</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with(model: @taichi_file, local: true) do |form| %>
            <div class="py-4 mx-2">
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "title"%>
            </div>
            <div class="py-4 mx-2">
              <%= form.label :category%>
              <%= form.select :category, options_for_select(["General","Qigong", "Form"]), {}, class: "custom-select custom-select-lg"%>
            </div>
            <div class="py-4 mx-2">
              <%= form.text_field :desc, class: "form-control form-control-lg", placeholder: "File description"%>
            </div>
            <div class="py-4 mx-2">
              <%= form.label :file_to_uploaded%>
              <br/>
              <span class="font-italic">
                pdfs are preferred
              </span>
              <%= form.file_field :docs, class: "form-control-file form-control-file-lg"%>
            </div>
            <div class="py-4 mx-2">
              <%= form.submit "Add File", class: "btn btn-success btn-lg"%>
            </div>
          <% end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/taichi_files/new.html.erb
<h1 class="py-4 text-center">New Taichi File</h1>

<%= render 'form', taichi_file: @taichi_file %>

app/views/taichi_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @taichi_file.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @taichi_file.desc %>
</p>

<p>
  <strong>Category:</strong>
  <%= @taichi_file.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @taichi_file.user %>
</p>

<%= link_to 'Edit', edit_taichi_file_path(@taichi_file) %> |
<%= link_to 'Back', taichi_files_path %>